# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d818fe3358f42ed31ad20ed23fbb832afd4d05186efa4aaa5ddf5d4c84ce6e3318b8ae819c8d70a4b164c65b235f02c360816b8686a321efeb7319da4c11d2a

test:
  secret_key_base: c8aa9f3d2d09e521f46a0c1a5d8103693061345af89b4a06af55607511d5e93d7996f3c2758b50723df94dede2a6bc9ad0ab39d0c7c84b6c866395eb594e32d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
